BEGIN TRANSACTION;
DROP TABLE IF EXISTS PRODUTOS;
CREATE TABLE PRODUTOS (
	PRODUTO_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	PRODUTO_NOME TEXT NOT NULL,
	PRODUTO_VALOR_UNITARIO FLOAT NOT NULL,
	PRODUTO_PRATELEIRA INTEGER NOT NULL,
	CONSTRAINT PRODUTOS_FK FOREIGN KEY (PRODUTO_PRATELEIRA) REFERENCES PRATELEIRAS(PRATELEIRA_ID) ON DELETE RESTRICT
);
DROP TABLE IF EXISTS PRATELEIRAS;
CREATE TABLE PRATELEIRAS(
    PRATELEIRA_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PRATELEIRA_NOME TEXT NOT NULL,
    PRATELEIRA_LOCALIZACAO TEXT NOT NULL
);
DROP TABLE IF EXISTS NOTAS;
CREATE TABLE NOTAS (
	NOTA_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NOTA_DATA_EMISSAO DATE NOT NULL,
	NOTA_NUMERO INTEGER NOT NULL,
	NOTA_CLIENTE INTEGER NOT NULL,
	NOTA_ATENDENTE INTEGER NOT NULL,
	CONSTRAINT NOTAS_FK FOREIGN KEY (NOTA_CLIENTE) REFERENCES CLIENTES(CLIENTE_ID),
	CONSTRAINT NOTAS_FK_1 FOREIGN KEY (NOTA_ATENDENTE) REFERENCES ATENDENTES(ATENDENTE_ID)
);
DROP TABLE IF EXISTS ITENSNOTAS;
CREATE TABLE ITENSNOTAS (
	ITENSNOTA_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	ITENSNOTA_SEQUENCIA INTEGER NOT NULL,
	ITENSNOTA_PRODUTO INTEGER NOT NULL,
	ITENSNOTA_QUANTIDADE INTEGER NOT NULL,
	ITENSNOTA_VALOR_UNITARIO FLOAT NOT NULL,
	ITENSNOTA_VALOR_TOTAL FLOAT NOT NULL,
	ITENSNOTA_NOTA_ID INTEGER NOT NULL,
	CONSTRAINT ITENSNOTAS_FK FOREIGN KEY (ITENSNOTA_NOTA_ID) REFERENCES NOTAS(NOTA_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
DROP TABLE IF EXISTS ATENDENTES;
CREATE TABLE ATENDENTES(
    ATENDENTE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ATENDENTE_NOME TEXT NOT NULL
);
DROP TABLE IF EXISTS CLIENTES;
CREATE TABLE CLIENTES(
    CLIENTE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CLIENTE_NOME TEXT NOT NULL,
    CLIENTE_TELEFONE TEXT NOT NULL,
    CLIENTE_CPF TEXT NOT NULL,
    CLIENTE_TOTAL_COMPRAS FLOAT, 
    ID_CIDADE INTEGE,
    CONSTRAINT CLI_CIDADE_FK FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE(CIDADE_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
DROP TABLE IF EXISTS CIDADE;
CREATE TABLE CIDADE (
	CIDADE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	CIDADE_NOME TEXT
);
COMMIT;