SELECT * FROM CLIENTES;

SELECT * FROM ATENDENTES;

SELECT PRATELEIRA_NOME, PRATELEIRA_LOCALIZACAO FROM PRATELEIRAS;

SELECT PRODUTO_ID, PRODUTO_NOME, PRODUTO_VALOR_UNITARIO
FROM PRODUTOS
ORDER BY PRODUTO_PRATELEIRA;

SELECT
    NOTAS.NOTA_NUMERO AS NUMERO,
    NOTAS.NOTA_DATA_EMISSAO AS DATA,
    ITENSNOTAS.ITENSNOTA_PRODUTO AS PRODUTO,
    ITENSNOTAS.ITENSNOTA_QUANTIDADE AS QTD,
    ITENSNOTAS.ITENSNOTA_VALOR_UNITARIO AS VALOR_UN,
    ITENSNOTAS.ITENSNOTA_VALOR_TOTAL AS VALOR_TOTAL,
    PRODUTOS.PRODUTO_NOME
FROM
    ITENSNOTAS,
    PRODUTOS,
    NOTAS
WHERE
    ITENSNOTA_NOTA_ID = 1 AND ITENSNOTA_PRODUTO = PRODUTO_ID AND ITENSNOTA_NOTA_ID = NOTA_ID;


